### ISSUE TITLE
Error: Chromosome in BAm file header

### ISSUE THREAD

**Issue by CS791** [dsturg/Spanki#8]
HI!

I am using Spanki first time. I was running the command line which popup with an error. Please see the detail command line and error:

"~/Splicing_Analysis/Tophat2_Output/Col-0_4C_Rep1$ ~/Splicing_Analysis/Spanki/bin/spankijunc -i accepted_hits.bam -g ~/Splicing_Analysis/Genome/TAIR10.gtf -m all -f ~/Splicing_Analysis/Genome/TAIR10.fa -o ~/Splicing_Analysis/Tophat2_Output/Col-0_4C_Rep1/
[Apr 18 11:26:54] Preparing output location /home/waqas/Splicing_Analysis/Tophat2_Output/Col-0_4C_Rep1/
#####################################################
#####################################################
[**   Setup   **] Running in ' all ' mode
[Apr 18 11:26:54] Making transcript to attribute lookup
[Apr 18 11:26:58] Convert GTF reference to SAM
[11:26:58] Loading reference annotation.
[%s] Convert SAM reference to BAM Apr 18 11:27:04
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::hts_open_format] Failed to open file /home/waqas/Splicing_Analysis/Tophat2_Output/Col-0_4C_Rep1//tmp//ref.bam
samtools index: failed to open "/home/waqas/Splicing_Analysis/Tophat2_Output/Col-0_4C_Rep1//tmp//ref.bam": No such file or directory
[Apr 18 11:27:04] Opening fasta file
[Apr 18 11:27:04] Reading alignments from accepted_hits.bam
[Apr 18 11:27:04] ERROR: Chromosomes in bam file header missing from fasta reference:
Pt,1,Mt,3,2,5,4"

Any suggestions and help are much appreciated.

Thank you
Regards

SC

**Comment by CS791** [comment]
Another issue

"E::hts_open_format] Failed to open file ./junctions_out//tmp//ref.bam
samtools index: failed to open "./junctions_out//tmp//ref.bam": No such file or directory
[Apr 28 10:28:20] Opening fasta file
[Apr 28 10:28:20] Reading alignments from AS_Analysis/testdata/male_r1.bam
[Apr 28 10:28:37] Trying to load annotation as bam
[E::hts_open_format] Failed to open file ./junctions_out//tmp//ref.bam
Traceback (most recent call last):
  File "/home/saurabh/anaconda2/bin/spankijunc", line 4, in <module>
    __import__('pkg_resources').run_script('spanki==0.5.0', 'spankijunc')
  File "/home/saurabh/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/saurabh/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/saurabh/anaconda2/lib/python2.7/site-packages/spanki-0.5.0-py2.7.egg/EGG-INFO/scripts/spankijunc", line 1494, in <module>
    
  File "/home/saurabh/anaconda2/lib/python2.7/site-packages/spanki-0.5.0-py2.7.egg/EGG-INFO/scripts/spankijunc", line 1184, in main
    
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 940, in pysam.libcalignmentfile.AlignmentFile._open
IOError: [Errno 2] could not open alignment file `./junctions_out//tmp//ref.bam`: No such file or directory"

Any help is much appreciated.

Kind regards
SC

**Comment by dsturg** [comment]
Thanks for reporting issues! 
For your first problem, I think the key is this line:

> "[Apr 18 11:27:04] ERROR: Chromosomes in bam file header missing from fasta reference:
> Pt,1,Mt,3,2,5,4"

There are chromosomes in your alignment file that are not included in the fasta file.  It may be that you don't need all the chromosomes (for example, maybe you aligned to a version of the reference that includes mitochondrial sequence, but you don't care about it for splice junction purposes).  Just make sure the fasta file and BAM header match, or supply the exact reference fasta you aligned to.

For the other issue, it looks like Spanki can't find a file:

> samtools index: failed to open "./junctions_out//tmp//ref.bam": No such file or directory

I can't be sure of the problem, but Spanki can be finicky about paths.  Can you tell if the file exists?  Is it not there, or is Spanki not seeing it?  If the former, it may have had a problem parsing the GTF file. If you can give the command that generated the error, I can perhaps tell if it is a path problem.

Cheers!

**Comment by CS791** [comment]
Thank you for your response. Yes I solved the first issue, it was a reference file problem.
For the second issue, here is the command line:
"(base) saurabh@saurabh-Latitude-E6230:~$ spankijunc -i ~/AS_Analysis/testdata/male_r1.bam -g ~/AS_Analysis/testdata/annotation/genemodels.gtf -f ~/AS_Analysis/testdata/fasta/myref.fa -o ~/AS_Analysis/testdata/Out-put/"

I haven't see any file in the tmp/ folder. I downloaded all the supporting package from annaconda2, including Spanki.

Thank you
Kind regards
SC
